Document: bdlicense
Title: Debian bdlicense Manual
Author: <insert document author here>
Abstract: This manual describes what bdlicense is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bdlicense/bdlicense.sgml.gz

Format: postscript
Files: /usr/share/doc/bdlicense/bdlicense.ps.gz

Format: text
Files: /usr/share/doc/bdlicense/bdlicense.text.gz

Format: HTML
Index: /usr/share/doc/bdlicense/html/index.html
Files: /usr/share/doc/bdlicense/html/*.html
